name: Train and Deploy on SageMaker

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      SAGEMAKER_BUCKET: sagemaker-${{ secrets.AWS_REGION }}-${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install pytest

      - name: Lint
        run: |
          pip install flake8
          flake8 src --max-line-length=120

      - name: Run tests
        run: |
          pytest tests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run training with SageMaker
        run: |
          python sagemaker_launcher.py
